// Bundles the Express server and the Electron main/preload for packaging.
// The React client is built separately via `vite build` (client/dist).
import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';

/**
 * `sourcemap` is here for the runtime log, not for a debugger. Every stack the log captures
 * (WP-69) is read by a developer out of a customer's diagnostics bundle, and without a map
 * every frame of it points at a column of `index.mjs`/`main.cjs` — 3.3 MB and 634 KB of
 * bundled JS, so the line number says nothing at all. The `.map` files therefore have to
 * *ship*: `files` in electron-builder.yml packs `**` under both dist folders, and
 * `scripts/check-package.mjs` pins all three inside the asar so a future packaging change
 * cannot quietly drop them. The loader written at the bottom of this file turns the maps on
 * for the process.
 *
 * `sourcesContent: false` keeps the map to mappings and file names. Node needs no more than
 * that to rewrite a frame, the original file is not on a customer's disk to be shown anyway
 * — and the default would embed the full TypeScript source of the server and of main into
 * every installer, which is both ~4 MB of download and the sources this build deliberately
 * does not ship (see the `no TypeScript sources` assertion in check-package.mjs).
 *
 * @type {import('esbuild').BuildOptions}
 */
const common = {
  bundle: true,
  platform: 'node',
  target: 'node20',
  logLevel: 'info',
  sourcemap: true,
  sourcesContent: false,
};

// Server → single ESM file. better-sqlite3 stays external (native, rebuilt by
// electron-builder); the createRequire banner lets any bundled CJS deps work.
await build({
  ...common,
  entryPoints: ['server/src/index.ts'],
  outfile: 'server/dist/index.mjs',
  format: 'esm',
  external: ['better-sqlite3'],
  banner: {
    js: "import{createRequire as ___cr}from'module';const require=___cr(import.meta.url);",
  },
});

// Electron main + preload → CJS (Electron's classic entry format). Main lands beside its
// loader rather than on the name package.json points at; see below.
for (const [entry, out] of [
  ['main', 'main.bundle'],
  ['preload', 'preload'],
]) {
  await build({
    ...common,
    entryPoints: [`electron/${entry}.ts`],
    outfile: `electron/dist/${out}.cjs`,
    format: 'cjs',
    external: ['electron'],
  });
}

/**
 * The two lines that make the maps above do anything for main.
 *
 * Node decides whether to keep a file's source map **while compiling that file**, before a
 * single statement of it runs — so `process.setSourceMapsEnabled(true)` can never map the
 * module it stands in. esbuild emits one compilation unit, which means the call cannot go
 * into `electron/main.ts`, nor into a `banner`: either way it is inside `main.bundle.cjs`,
 * already compiled, and every main-process frame in the runtime log stays `main.cjs:89873`.
 * Verified both ways before this loader existed.
 *
 * Hence a real second file, compiled first. It keeps the name `package.json#main` and
 * electron-builder already know, so nothing outside this script moves; the 634 KB bundle it
 * pulls in is the file next to it, and that one gets its frames rewritten. The server bundle
 * needs no such care — main imports it long after this call.
 *
 * Written rather than committed so the two names cannot drift apart, and left in CJS: the
 * loader is the entry point, and Electron's is `require`-based.
 */
writeFileSync(
  'electron/dist/main.cjs',
  [
    '// Generated by scripts/build.mjs — do not edit.',
    '// Enables source maps for everything compiled after this line, which is the whole app.',
    'process.setSourceMapsEnabled(true);',
    "require('./main.bundle.cjs');",
    '',
  ].join('\n'),
);

console.log('✓ bundled server + electron');
